version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:${MYSQL_VERSION}
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - ${MYSQL_HOST}:${MYSQL_PORT}:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    restart: always
    ports:
      - ${POSTGRES_HOST}:${POSTGRES_PORT}:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    entrypoint: sh /docker-entrypoint.sh
    ports:
      - ${REDIS_HOST}:${REDIS_PORT}:6379
    volumes:
      - ./redis/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./redis/data:/data
    environment:
      REDIS_CONFIG: |
        dir /data
        requirepass ${REDIS_PASSWORD}

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: secret_minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001

  elasticsearch:
    container_name: elasticsearch
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    ports:
      - ${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}:9200
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    ports:
      - ${KIBANA_HOST}:${KIBANA_PORT}:5601
    environment:
      - I18N_LOCALE=${KIBANA_LANGUAGE}

  facebook_ads_manager_bullboard:
    container_name: bullboard
    image: addono/bull-board
    restart: always
    ports:
      - 3004:3000
    environment:
      REDIS_HOST: ${FACEBOOK_AD_MANAGER_BULL_HOST}
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${FACEBOOK_AD_MANAGER_BULL_PASSWORD}
      REDIS_DB: 10
      REDIS_USE_TLS: 'false'
      BULL_PREFIX: bull
  bullboard:
    container_name: bullboard
    image: addono/bull-board
    restart: always
    ports:
      - 3003:3000
    environment:
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 63791
      # REDIS_PASSWORD: secret
      REDIS_USE_TLS: 'false'
      BULL_PREFIX: bull

  node-dev:
    container_name: node
    image: node:16
    ports:
      - 3000:3000
    volumes:
      - ~/Projects:/app
    # command: bash
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:

volumes:
  minio_data:
