version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - ${MYSQL_HOST}:${MYSQL_PORT}:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    ports:
      - ${POSTGRES_HOST}:${POSTGRES_PORT}:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    entrypoint: sh /docker-entrypoint.sh
    ports:
      - ${REDIS_HOST}:${REDIS_PORT}:6379
    volumes:
      - ./redis/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./redis/data:/data
    environment:
      REDIS_CONFIG: |
        dir /data
        requirepass ${REDIS_PASSWORD}
